spring:
  devtools:
    restart:
      additional-paths: src/main/java,src/main/resources
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/blog
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
  thymeleaf:
    cache: false
server:
  servlet:
    session:
      persistent: false

