spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blog
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true